@startuml

package "Платформа аренды" {
  [Веб-интерфейс] --> [Бизнес-логика]

  package "Бизнес-логика" {
   [Сервис пользователей]
   [Сервис объявлений]
   [Сервис бронирований]
   [Сервис рейтингов]
  }

  [База данных]-->[Бизнес-логика]
}

@enduml